import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { config } from "dotenv";
config({ path: [".env.local", ".env"] });

// Pre-generates explanations for every seeded finding in every language, so
// the demo works even when the LLM API is down or rate-limited.
// Writes them to Neon (source = "cached") and to data/explanations.seed.json,
// which is the fallback when there is no database and in mock mode.
//
//   npm run pregen

const LANGS = ["en", "es", "zh", "ko"] as const;

async function main() {
  const { explainFinding, getProvider } = await import("../lib/llm");
  const { currentDetection } = await import("../lib/checkup/findings");
  if (!getProvider()) throw new Error("No LLM provider key set (XAI_API_KEY). Nothing to pre-generate.");

  // The fixture gives the same finding ids as Nessie (ids use dates, not source ids).
  const { findings, billEvents } = await currentDetection({ mock: true });
  const noCache = { get: async () => null, set: async () => {} };
  const out: Record<string, { body: string; enBody: string; source: "cached" }> = {};
  const failed: string[] = [];

  const jobs = findings.flatMap((f) => LANGS.map((lang) => ({ f, lang })));
  let i = 0;
  await Promise.all(
    Array.from({ length: 4 }, async () => {
      while (i < jobs.length) {
        const { f, lang } = jobs[i++];
        const e = await explainFinding(f, lang, { billEvents, cache: noCache });
        if (e.source === "llm") {
          out[`${f.id}:${lang}`] = { body: JSON.stringify(e.body), enBody: JSON.stringify(e.en), source: "cached" };
          console.log(`  ✓ ${f.display} (${f.type}) ${lang}`);
        } else {
          failed.push(`${f.display} ${lang}: ${e.fallbackReason}`);
          console.log(`  ✗ ${f.display} (${f.type}) ${lang}: template (${e.fallbackReason})`);
        }
      }
    }),
  );

  const file = join(process.cwd(), "data", "explanations.seed.json");
  const sorted = Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)));
  writeFileSync(
    file,
    JSON.stringify(
      {
        _note: "Pre-generated by scripts/pregen-explanations.ts from the LLM, validated against the detector's numbers. Used when the API or database is unavailable, and in mock mode.",
        generated: new Date().toISOString().slice(0, 10),
        explanations: sorted,
      },
      null,
      2,
    ) + "\n",
  );
  console.log(`\nWrote ${Object.keys(out).length} explanations to ${file}`);

  if (process.env.DATABASE_URL) {
    const { getDb } = await import("../lib/db/client");
    const { explanations } = await import("../lib/db/schema");
    const db = getDb();
    for (const [key, v] of Object.entries(out)) {
      const [findingId, lang] = key.split(":");
      await db
        .insert(explanations)
        .values({ findingId, lang, body: v.body, enBody: v.enBody, source: "cached" })
        .onConflictDoUpdate({
          target: [explanations.findingId, explanations.lang],
          set: { body: v.body, enBody: v.enBody, source: "cached", generatedAt: new Date() },
        });
    }
    console.log(`Stored ${Object.keys(out).length} in Neon as source=cached.`);
  }
  if (failed.length) console.log(`\n${failed.length} fell back to templates (the app will use templates for these):\n  ${failed.join("\n  ")}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
